// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package xvalue

import "strconv"

const _Kind_name = "InvalidBoolIntInt8Int16Int32Int64UintUint8Uint16Uint32Uint64Float32Float64StringObjectUserData"

var _Kind_index = [...]uint8{0, 7, 11, 14, 18, 23, 28, 33, 37, 42, 48, 54, 60, 67, 74, 80, 86, 94}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
